import { getAllFloors } from '@/models/Floor'
import Link from 'next/link'
import React from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params }) {
  const buildingId = await params
  const floors = await getAllFloors()

  return (
    <>
      <div>
        <div className="flex justify-between items-center mb-[40px]">
          <h1 className="text-[32px] font-bold mt-[40px]">Thu Thet Thar</h1>
          <Link href={'/buildings'} className="font-bold">
            Back
          </Link>
        </div>
        <div className="flex justify-between items-center mb-[24px]">
          <h1 className="font-bold text-[24px] text-[#4F378B]">boy rooms</h1>
          <Link href={'/buildings/create-floor'} className="flex items-center">
            <p className="mr-[8px]">Create Floor</p>
            <img
              src="/system-icons/plus-circle.png"
              className="w-[24px] h-[24px]"
            />
          </Link>
        </div>
        <div className="flex gap-[24px]">
          {floors.map((floor, index) => (
            <Link
              key={index}
              href={`/buildings/${buildingId.id}/${floor.id}`}
              className={`w-[253px] h-[192px] `}
            >
              <img
                src={floor.img}
                className="h-[152px] w-[253px] rounded-[16px] shadow-lg"
              />
              <p className="mt-[16px] font-bold">{floor.name}</p>
            </Link>
          ))}
        </div>
      </div>
      <div>{children}</div>
    </>
  )
}
